### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by Poonam-Kashyap12** [recodehive/Support#130]
### Name

Poonam kashyap

### Discord Username (if applicable)

poonamkashyap_61451

### Additional Context

I love to explore new things and want to learn about them ,I think that's the best way to learn about new things

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
