### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by yashksaini-coder** [recodehive/Support#133]
### Name

Yash Kumar Saini

### Discord Username (if applicable)

lonely_coder_007

### Additional Context

I love Data science and wants to explore more in this field.

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
