### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by mdazfar2** [recodehive/Support#138]
### Name

Azfar Alam

### Discord Username (if applicable)

mdazfar2

### Additional Context

I admire this community's commitment to fostering collaboration and innovation. Joining will allow me to contribute my DevOps expertise, learn from talented members, and further enhance our collective knowledge. I am excited to grow together and achieve remarkable milestones.

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
