### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by abdullahazharkhan** [recodehive/Support#156]
### Name

Abdullah Azhar Khan

### Discord Username (if applicable)

@pov_abdullah

### Additional Context

Hey, this is Abdullah Azhar Khan, and I'm from Pakistan. I got to know about this community from your profile. I'm very much excited in your community, as I am new in the open-source community, and I want to contribute to the real projects, in order to gain experience. You can know more about me at: [abdullahazhar.me](https://abdullahazhar.me)

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
