### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by ISmokeData** [recodehive/Support#162]
### Name

Dhanraj Verma

### Discord Username (if applicable)

.jmd.

### Additional Context

Joining in this community offers numerous benefits for both personal and professional growth. Firstly, it provides access to a wealth of knowledge and resources, allowing members to stay updated with the latest trends, tools, and techniques in the rapidly evolving field of data science. Engaging with a community of like-minded individuals fosters collaboration and networking, enabling the exchange of ideas, problem-solving strategies, and best practices.

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
