### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by UjjwalSaini07** [recodehive/Support#175]
### Name

Ujjwal Saini

### Discord Username (if applicable)

ujjwalsaini0007

### Additional Context

I wanted to work with this community and organization and contribute to make it more enhancing and also it helpful for mine to get new skills from seniors.
My profile - [Link- UjjwalSaini07](https://github.com/UjjwalSaini07)

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>

**Comment by UjjwalSaini07** [comment]
Hii Sir, 
Sir where i get accepting link.
