### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by alpharsh** [recodehive/Support#177]
### Name

Harsh Tripathi

### Discord Username (if applicable)

alpharsh

### Additional Context

I've seen that this community is more active and I've just aced the GSSOC'24 and want to keep my contributions and learnings keep going on, I feel this community has the right set to provide me with the right experience and guidance.

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
