### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by Aradhya-005** [recodehive/Support#234]
### Name

Aradhya 

### Discord Username (if applicable)

aradhya_16041

### Additional Context

I'm excited to start my journey as a beginner open-source contributor! I'm looking forward to learning from and collaborating with the community to improve my skills and contribute to innovative projects. I'm eager to be a part of this community and help make open-source software even better!✌️.

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
