### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by akashlogics** [recodehive/Support#242]
### Name

akashogics

### Discord Username (if applicable)

akashr0023

### Additional Context

I am a student of B.tech Artificial Intelligence and Data Science and studying 3rd year I am interested in joining the community to learn some real-world problems and learn from professionals by open source project
participated in GSsoc'24 and made 2PR and completed API postman
I will thankful for joining in the commmunity

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
