### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by PayalKumari10** [recodehive/Support#247]
### Name

Payal Kumari

### Discord Username (if applicable)

payalkumari_

### Additional Context

What I Like About This Community:

I admire Recode-Hive’s strong commitment to fostering open-source collaboration and learning. It’s incredible how this community provides such a welcoming space for contributors of all levels, encouraging participation through issues, pull requests, and shared ideas. I particularly appreciate the focus on helping members improve their skills while making meaningful contributions to open-source projects. The combination of learning resources like the GitHub profile course and the practice repo for Hacktoberfest participants shows how dedicated the community is to growth and inclusivity.

Why I Want to Join:

As someone passionate about open source and continuously learning, I’m eager to join this dynamic community to contribute, collaborate, and expand my skills. The structure of Recode-Hive, with its open discussions, good first issues, and supportive network, aligns with my goals of improving as a developer and giving back to the open-source ecosystem. I’m excited to be part of a group that values helping others and driving impactful innovations together.

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
