### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by Nikhiljangra04** [recodehive/Support#253]
### Name

Nikhil

### Discord Username (if applicable)

gamechanger401

### Additional Context

In the previous month, I attended a topmate meet hosted by program manager of GSSoC'24 @sanjay-kv . There I came to know about this organization. As suggested, we should join the organizations for making contributions , now I want to make contributions and eager to join this organization so that I can make contributions to it and also it would help me to improve  my Github profile.

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
