### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by MAVRICK-1** [recodehive/Support#258]
### Name

Rishi Mondal

### Additional Context

I am excited to join the Recode-Hive GitHub Community Organization because I admire the culture of innovation, collaboration, and open-source contributions that the community fosters. It provides a unique platform to connect with passionate developers, contribute to impactful projects, and continuously grow as a developer. I am eager to share my skills, learn from others, and collaborate on meaningful initiatives that drive technological advancements. Recode-Hive's focus on collective problem-solving and knowledge sharing is something I deeply resonate with, and I look forward to becoming an active part of this vibrant community.

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
