### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by gayu999Code** [recodehive/Support#271]
### Name

Gayatri Maruti Mohite

### Discord Username (if applicable)

gayatri | Contributor

### Additional Context

1. Showcase your skills and contributions to potential employers.
2. Develop a strong GitHub profile.
3. Demonstrate ability to work collaboratively.
4. Encourages members to share ideas, help each other, and make improvements.
5.  Network with like-minded individuals.

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
