### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by grasyPatel** [recodehive/Support#272]
### Name

Grace Patel

### Discord Username (if applicable)

gracepatel

### Additional Context

I am really drawn to this community because of its collaborative and supportive environment. I appreciate the opportunity to contribute to meaningful projects while learning from experienced developers.
By joining this community, I hope to not only grow my technical skills but also share my own knowledge and experiences with others.

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
