### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by jinx-vi-0** [recodehive/Support#280]
### Name

Adarsh

### Discord Username (if applicable)

jinx.vi

### Additional Context

I appreciate the sense of support and collaboration within this community. The opportunity to connect with like-minded individuals and share experiences is invaluable. I'm eager to contribute and learn from everyone here.

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
