### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by vprathap21** [recodehive/Support#303]
### Name

prathap v

### Discord Username (if applicable)

prathap._

### Additional Context

I’m genuinely excited about this project because it aligns with my interests and goals. I want to contribute my skills to help enhance its functionality and usability. Being part of this community would not only allow me to support a project I admire but also learn from like-minded individuals who are passionate about making a difference

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
