### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by Shiva-Bajpai** [recodehive/Support#306]
### Name

Shiva Bajpai

### Discord Username (if applicable)

shivabajpai

### Additional Context

I'm Shiva, a passionate developer and sophomore engineering student with a keen interest in web development and software engineering. I have experience working with technologies like JavaScript, React, Next.js, and C++, and I'm always eager to learn and collaborate on exciting projects. I want to be a part of your organization and contribute to the community while sharing knowledge with fellow developers. Let's build something amazing together!

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
