### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by skmirajulislam** [recodehive/Support#315]
### Name

Sk Mirajul Islam

### Discord Username (if applicable)

sk_miraj

### Additional Context

I am excited to join this community because it’s a hub of collaboration, innovation, and learning. The open-source ecosystem thrives here, offering endless opportunities to contribute to impactful projects, learn from experienced developers, and grow as a professional. By engaging in this community, I hope to share my skills, collaborate with diverse teams, and improve both my technical abilities and my understanding of collaborative software development. The community’s focus on mentorship and fostering an inclusive environment aligns with my desire to give back and learn through hands-on experiences.

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>

**Comment by skmirajulislam** [comment]
Sure, thank you so much!
