### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by Ashut2** [recodehive/Support#326]
### Name

Ashutosh Shukla | Contributor

### Discord Username (if applicable)

ashutoshshukla831888

### Additional Context

Helping others and get saved by others were always my type of things. This community aligns with my core values to encourage , inspire and collabrate with amazing minds out there . and that's the reason why i am here .

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
