### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by Sandigupta** [recodehive/Support#328]
### Name

Sandeep Gupta

### Discord Username (if applicable)

sandip_g

### Additional Context

The GitHub community is a hub for collaboration, innovation, and learning. It brings together developers of all skill levels to contribute to open-source projects, share knowledge, and improve code quality. I’m also a beginner in open-source, and it’s an inspiring space for growth and problem-solving.

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>

**Comment by Sandigupta** [comment]
Thanks
