### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by hamzathul** [recodehive/Support#342]
### Name

Hamzathul Favas E

### Discord Username (if applicable)

hamzathul

### Additional Context

I am an aspiring MERN stack developer with a strong interest in open source contributions. I'm passionate about building web applications using MongoDB, Express, React, and Node.js, and I’m eager to collaborate with other developers. I’m also excited to learn new skills, explore different technologies, and grow as a developer alongside this community. I look forward to contributing and learning with everyone here.

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
