### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by Sadab-Hussain** [recodehive/Support#344]
### Name

Sadab Hussain

### Discord Username (if applicable)

Sadab Hussain | Contributor

### Additional Context

To learn more and dive deeper into open source.

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>

**Comment by Sadab-Hussain** [comment]
I noticed that my name is not appearing in the GitHub organization list. Could you please check if I’ve been added properly or let me know if there’s any additional step I need to take to be listed?
