### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by aditya-technophile-06** [recodehive/Support#349]
### Name

Aditya M

### Discord Username (if applicable)

aditya_m_06

### Additional Context

I’d love to join Recode Hive because it feels like such a welcoming and inclusive community, especially for someone like me who’s passionate about data science. I really like how open it is, encouraging people to jump in, share ideas, and learn together. The focus on open-source collaboration and helping each other grow is exactly what I’m looking for. Plus, being able to improve my GitHub profile and get involved in meaningful projects with other like-minded people is a huge bonus. It seems like a great place to develop my skills and connect with others who are just as enthusiastic about data science and open-source as I am.

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
