### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by SimranShaikh20** [recodehive/Support#357]
### Name

Simran Shaikh

### Additional Context

I like to work with recodehive because i want work for this organisation . I want to work for data anlysis and machine learning feild and to explore more in this feild . By joining this community it will help me more .
@sanjay-kv please add me for this organization .

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
