### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by shivi13102** [recodehive/Support#359]
### Name

CH Shivangi

### Discord Username (if applicable)

shivangi_51686

### Additional Context

Hi, I am one of the GSSoC contributors of 2024ext. I have learned a lot from your videos about GitHub and would like to continue with you guys to get more updates about GitHub.

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
