### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by arpita205** [recodehive/Support#360]
### Name

Arpita Mittal

### Discord Username (if applicable)

arpita205

### Additional Context

I would like to join this community because I want to address issues and add new features to the projects .

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>

**Comment by arpita205** [comment]
My name is not the list . Could you please help.
