### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by Robinbinu** [recodehive/Support#380]
### Name

Michael Robin K

### Discord Username (if applicable)

robin303557

### Additional Context

I wish to become a contributor because I am passionate about open-source projects and want to improve my skills as a developer while working with others in a collaborative environment. I believe contributing to open source will help me grow as a software engineer and allow me to create meaningful impacts in the community.

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
