### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by RanitDERIA** [recodehive/Support#384]
### Name

Ranit Deria

### Discord Username (if applicable)

ranitderia

### Additional Context

- I admire the collaborative spirit of the Recode-Hive community, which fosters learning and growth among developers. 
- Joining this organization would allow me to contribute, learn from others, and work together on exciting open-source projects. 
- I am eager to be a part of this community and help in building innovative solutions while sharing my knowledge and skills.

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
