### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by shivhere007** [recodehive/Support#388]
### Name

Shivam Prasad Singh

### Discord Username (if applicable)

shiv007_70175

### Additional Context

Please invite me to the Recode-Hive GitHub Community Organization. I'm excited to connect with like-minded developers, contribute to innovative projects, and grow in a supportive community. With my passion for open-source and commitment to continuous learning, I’m eager to make meaningful contributions. I look forward to sharing knowledge, gaining insights, and helping build impactful projects together.

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
