### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by idimetrix** [recodehive/Support#389]
### Name

Dmitry Selikhov

### Discord Username (if applicable)

idimetrix

### Additional Context

I'm open source advocate and love to do open source contributions:

🚀CTO, 🏗️Software Architect, 🧑‍💻Technical Lead, 👨‍💼3X Founder. 🔗Linking companies with top tech talents.

CV: [https://dmitrii-selikhov.vercel.app](https://dmitrii-selikhov.vercel.app)
GitHub: [https://github.com/idimetrix](https://github.com/idimetrix)
LinkedIn: [https://www.linkedin.com/in/dimetrix](https://www.linkedin.com/in/dimetrix)

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
