### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by techy4shri** [recodehive/Support#401]
### Name

Garima

### Discord Username (if applicable)

techy4shri

### Additional Context

I heard about this organisation while going through the GSSoC info here on github and then I got the chance to work with this, I like how we can compare and just basically explore github like a social web.

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
