### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by myselfshivams** [recodehive/Support#402]
### Name

Shivam

### Additional Context

I am really inspired by your community and the way it supports growth. The super awesome profile review session was especially motivating it showed me how much care goes into helping everyone improve and reach their best. Being part of this group would be an amazing opportunity to learn, contribute, and keep pushing my skills forward.

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
