### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by sanchitc05** [recodehive/Support#403]
### Name

Sanchit Chauhan

### Discord Username (if applicable)

sanchitchauhan7868

### Additional Context

I'm writing to express my interest in joining Recodehive, an open-source community for data science enthusiasts. I've been following Recodehive's work on machine learning and AI for some time now, and I'm impressed by the organization's commitment to OPEN SOURCE contributions, especially in the field of Data Science is what motivates me to be a part of it.

I'm a data science student currently in 2nd year of college. I'm passionate about training models and deriving useful information from raw data and I'm always eager to learn and grow my skills.

I believe that my skills would be a valuable asset to Recodehive. I'm particularly interested in contributing to machine learning repos. I'm also a strong believer in the power of open-source communities to accelerate innovation.

I've attached my resume for your review. Thank you for your time and consideration.

Sincerely,
Sanchit Chauhan

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
