### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by MadhavDhatrak** [recodehive/Support#425]
### Name

Madhav dhatrak

### Discord Username (if applicable)

madhavdhatrak

### Additional Context

I am a dedicated software developer with experience in full stack development, DevOps, and open-source contributions. I am also a Microsoft Learn Student Ambassador, which has given me experience in community building and teaching tech skills to peers I am passionate about sharing knowledge and helping others learn about software development, particularly in areas like APIs, and DevOps 

Recode-Hive's mission aligns perfectly with my own goals as I am actively seeking opportunities to collaborate with other developers, contribute to open-source projects, and grow my skills in new tech areas. I believe I can add value to the community by contributing to ongoing projects and sharing resources with other members.

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
