### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by dipexplorer** [recodehive/Support#435]
### Name

dipexplorer

### Additional Context

I would love to be part of this awesome community because I am passionate about contributing to open-source projects, collaborating with like-minded developers, and enhancing my skills.

I’ve earned Rank 27 in the GSSoC 2024 Extended Edition, which highlights my commitment to open-source contributions.

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
