### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by Rohinipilla** [recodehive/Support#450]
### Name

PILLA ROHINI

### Discord Username (if applicable)

pillarohini_43306

### Additional Context

I want to learn from smart people who know a lot about coding. I think this group is a good place to practice and get better at coding. I want to help the group and make cool stuff with other people.

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
