### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by Shriharsh-Deshmukh** [recodehive/Support#466]
### Name

Shriharsh-Deshmukh

### Additional Context

I admire this community's commitment to fostering collaboration and innovation through impactful projects. The supportive and inclusive environment, combined with the opportunity to learn from talented developers, inspires me to contribute and grow as a coder. Joining this community would allow me to be part of meaningful work while exchanging knowledge and ideas with like-minded individuals passionate about technology.

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
