### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by Wahid7852** [recodehive/Support#468]
### Name

Wahid Khan

### Discord Username (if applicable)

wahid_2584

### Additional Context

Recode Hive is an emerging online platform dedicated to application development, programming queries, voice apps, and tech reviews. The community actively engages in initiatives like the "Share Your Script Campaign," which focuses on collecting diverse handwriting samples to enhance optical character recognition (OCR) models for various languages.

Yeah... I love it

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
