### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by deepakcode21** [recodehive/Support#471]
### Name

Deepak

### Discord Username (if applicable)

arrowmx

### Additional Context

I am passionate about open-source development and believe that joining the Recode-Hive community will help me learn, collaborate, and contribute effectively to impactful projects. Being part of this community will allow me to connect with like-minded developers, improve my coding skills, and share my knowledge while learning from others. Additionally, I am excited about the opportunity to work on real-world projects and grow as a developer within a supportive and innovative environment.

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/recodehive/people<br><br>
